Commit changes made by code formatters

diff --git a/playbooks/oracle_ha/disable-fsfo.yml b/playbooks/oracle_ha/disable-fsfo.yml
--- a/playbooks/oracle_ha/disable-fsfo.yml
+++ b/playbooks/oracle_ha/disable-fsfo.yml
@@ -4,9 +4,9 @@
   become_user: oracle
   become_method: sudo
   tasks:
-      - name: Disable FSFO if Enabled
-        shell: |
-          . ~/.bash_profile
-          echo "show fast_start failover" | dgmgrl / | grep "Fast-Start Failover: Enabled" && echo "disable fast_start failover" | dgmgrl / || true
-        register: disable_fsfo
-        changed_when: disable_fsfo.stdout | default('') is search('.*Disabled.*')
+    - name: Disable FSFO if Enabled
+      shell: |
+        . ~/.bash_profile
+        echo "show fast_start failover" | dgmgrl / | grep "Fast-Start Failover: Enabled" && echo "disable fast_start failover" | dgmgrl / || true
+      register: disable_fsfo
+      changed_when: disable_fsfo.stdout | default('') is search('.*Disabled.*')
