error check for s3 deletion

diff --git a/.github/workflows/ldap-data-refresh.yml b/.github/workflows/ldap-data-refresh.yml
--- a/.github/workflows/ldap-data-refresh.yml
+++ b/.github/workflows/ldap-data-refresh.yml
@@ -460,14 +460,18 @@ jobs:
 
           # delete datasync task
           aws datasync delete-task --task-arn ${{ needs.source.outputs.DATASYNC_TASK_ARN }}
-
           # delete location for for temp EFS
           aws datasync delete-location --location-arn ${{ needs.source.outputs.DATASYNC_SOURCE_LOCATION_ARN }}
-
           # delete location for S3
           aws datasync delete-location --location-arn ${{ needs.source.outputs.DATASYNC_DESTINATION_LOCATION_ARN }}
 
       - name: Remove S3 directory
         run: |
-
+          echo "Removing S3 directory ${{ needs.destination.outputs.DIRECTORY }}... "
           aws s3 rm s3://${{ github.event.inputs.destination_env }}-ldap-data-refresh-incoming/${{ needs.destination.outputs.DIRECTORY }} --recursive
+          if [[ $? -eq 0 ]]; then
+            echo "S3 directory ${{ needs.destination.outputs.DIRECTORY }} removed"
+          else
+            echo "Failed to delete S3 directory ${{ needs.destination.outputs.DIRECTORY }}"
+            exit 1
+          fi
