create job outputs

diff --git a/.github/workflows/ldap-data-refresh.yml b/.github/workflows/ldap-data-refresh.yml
--- a/.github/workflows/ldap-data-refresh.yml
+++ b/.github/workflows/ldap-data-refresh.yml
@@ -83,6 +83,7 @@ jobs:
           #          fi
           
           echo "Copying from ${source_env} to ${destination_env}"
+
   destination-pre:
     needs:
         - pre-checks
@@ -270,6 +271,13 @@ jobs:
                 fi
             done
             echo "Datasync task from ${{ github.event.inputs.source_env }} to ${{ github.event.inputs.destination_env }} completed. Switching to destination account"
+    outputs:
+      TEMP_EFS_ID: ${{ steps.get-temp-efs-id.outputs.TEMP_EFS_ID }}
+      SUBNET_IDS: ${{ steps.get-ec2-config.outputs.SUBNET_IDS }}
+      DATASYNC_SOURCE_LOCATION_ARN: ${{ steps.create-datasync-location.outputs.DATASYNC_SOURCE_LOCATION_ARN }}
+      DATASYNC_DESTINATION_LOCATION_ARN: ${{ steps.create-datasync-destination-location.outputs.DATASYNC_DESTINATION_LOCATION_ARN }}
+
+
   destination:
     needs:
       - source
@@ -385,18 +393,18 @@ jobs:
         run: |
 
           # Delete the access point
-          aws efs delete-access-point --access-point-id ${{ steps.get-temp-efs-id.outputs.TEMP_EFS_ID }} --output text --query 'AccessPointId'
+          aws efs delete-access-point --access-point-id ${{ needs.cleanup.outputs.TEMP_EFS_ID }} --output text --query 'AccessPointId'
           if [[ $? -eq 0 ]]; then
-              echo "Access point ${{ steps.get-temp-efs-id.outputs.TEMP_EFS_ID }} deleted"
+              echo "Access point ${{ needs.cleanup.outputs.TEMP_EFS_ID }} deleted"
           else
-              echo "Failed to delete access point ${{ steps.get-temp-efs-id.outputs.TEMP_EFS_ID }}"
+              echo "Failed to delete access point ${{ needs.cleanup.outputs.TEMP_EFS_ID }}"
               exit 1
           fi
 
           # Delete the mount targets
-          IFS=',' read -ra SUBNETS <<< "${{ steps.get-ec2-config.outputs.SUBNET_IDS }}"
+          IFS=',' read -ra SUBNETS <<< "${{ needs.cleanup.outputs.SUBNET_IDS }}"
           for subnet in "${SUBNETS[@]}"; do
-            mount_target_id=$(aws efs describe-mount-targets --file-system-id ${{ steps.get-temp-efs-id.outputs.TEMP_EFS_ID }} --subnet-id $subnet --query 'MountTargets[0].MountTargetId' --output text)
+            mount_target_id=$(aws efs describe-mount-targets --file-system-id ${{ needs.cleanup.outputs.TEMP_EFS_ID }} --subnet-id $subnet --query 'MountTargets[0].MountTargetId' --output text)
             if [ -n "$mount_target_id" ]; then
               aws efs delete-mount-target --mount-target-id "$mount_target_id" --output text
               if [[ $? -eq 0 ]]; then
@@ -407,11 +415,23 @@ jobs:
               fi
             fi
           done
+
+      - name: Remove temporary EFS
+        run: |
+
+          aws efs delete-file-system --file-system-id ${{ needs.cleanup.outputs.TEMP_EFS_ID }} 
+          if [[ $? -eq 0 ]]; then
+            echo "File system ${{ needs.cleanup.outputs.TEMP_EFS_ID }}  deleted"
+          else
+            echo "Failed to delete file system ${{ needs.cleanup.outputs.TEMP_EFS_ID }}"
+            exit 1
+          fi
+
       - name: Clear up datasync locations
         run: |
 
           # for temp EFS
-          aws datasync delete-location --location-arn ${{ steps.create-datasync-location.outputs.DATASYNC_SOURCE_LOCATION_ARN }}
+          aws datasync delete-location --location-arn ${{ needs.cleanup.outputs.DATASYNC_SOURCE_LOCATION_ARN }}
 
           # for S3
-          aws datasync delete-location --location-arn ${{ steps.create-datasync-destination-location.outputs.DATASYNC_DESTINATION_LOCATION_ARN }}
+          aws datasync delete-location --location-arn ${{ needs.cleanup.outputs.DATASYNC_DESTINATION_LOCATION_ARN }}
